// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

// Injectors from wire.go:

func InitializeService() *dynamodb.Client {
	config := initializeAwsConfig()
	client := initializeDynamoDB(config)
	return client
}
